version: '3.6'
services:
  zookeeper:
    container_name: ship-zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - ship
  kafka:
    container_name: ship-kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - ship
    depends_on:
      - zookeeper
  mongo:
    container_name: ship-mongo
    image: mongo:4.2
    command: --replSet ship-rs --bind_ip_all
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - ship
    ports:
      - 27017:27017
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongo-replicator:
    container_name: ship-mongo-replicator
    build: ./mongo-replicator
    environment:
      - HOST=mongo
      - PORT=27017
      - USERNAME=root
      - PASSWORD=root
      - REPLICA_SET_NAME=ship-rs
    networks:
      - ship
    depends_on:
      - mongo
  redis:
    container_name: ship-redis
    image: redis:5.0.5
    command: redis-server --appendonly yes
    hostname: redis
    networks:
      - ship
    ports:
      - 6379:6379
  api:
    container_name: ship-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - ship
    environment:
      APP_ENV: development
    volumes:
      - ./src:/app/src
    ports:
      - 3001:3001
      - 8082:8082
    depends_on:
      - mongo-replicator
      - redis

  user-signup-handler:
    container_name: ship-user-signup-handler
    build:
      context: ./user-signup-handler
      dockerfile: Dockerfile.dev
    networks:
      - ship
    volumes:
      - ./user-signup-handler/src:/app/src

  migrator:
    container_name: ship-migrator
    command: npm run migrate
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - ship
    volumes:
      - ./src:/app/src
    depends_on:
      - mongo-replicator
  scheduler:
    container_name: ship-scheduler
    command: npm run schedule-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - ship
    volumes:
      - ./src:/app/src
    depends_on:
      - mongo-replicator

networks:
  ship:
    name: ship-network
